# Generated by Django 2.2.1 on 2019-06-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_auto_20190602_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='permission',
            field=models.CharField(choices=[('admin', 'administrator'), ('user', 'generaluser')], default='generaluser', max_length=30),
        ),
    ]
