# Generated by Django 2.2.1 on 2019-06-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_auto_20190607_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('grade', models.CharField(max_length=4)),
                ('studentid', models.CharField(max_length=13, unique='true')),
                ('college', models.CharField(max_length=20)),
                ('profession', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'student',
                'verbose_name_plural': 'student',
                'ordering': ['studentid'],
            },
        ),
    ]
