# Generated by Django 2.2.1 on 2019-06-07 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='studentname',
        ),
    ]
