# Generated by Django 2.2.1 on 2019-06-07 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_auto_20190607_2150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='studentname',
            new_name='name',
        ),
    ]
