# Generated by Django 2.2.1 on 2019-06-08 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_auto_20190607_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('studentid', models.CharField(max_length=13, unique='true')),
                ('Chinese', models.CharField(max_length=20)),
                ('Mathematics', models.CharField(max_length=20)),
                ('English', models.CharField(max_length=20)),
                ('Physical', models.CharField(max_length=20)),
                ('Chemistry', models.CharField(max_length=20)),
                ('PE', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'grade',
                'verbose_name_plural': 'grade',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['id'], 'verbose_name': 'student', 'verbose_name_plural': 'student'},
        ),
    ]
